FROM ollama/ollama:latest

# Install curl
RUN apt-get update && apt-get install -y curl

# Copy entrypoint.sh into the container
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# Make sure entrypoint.sh is executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
