version: "4.9"
networks:
  fullstack:
    driver: bridge

services:
  app:
    networks:
      - fullstack
    container_name: system-monitor
    build: .
    command: ["./system-monitor", "run"]
    image: system-monitor:latest
    restart: unless-stopped
    ports:
      - '8741:8741'
    volumes:
      - api:/usr/src/app/
volumes:
  api:
